---
title: "Lehr- und Vortragsmaterial"
author: "Dr. Heiko Etzold, Universität Potsdam"
output:
  html_document: default
---

## Akademische Grundkompetenzen

* [Lineare Regression / Methode der kleinsten Quadrate](linReg/linReg.html)

## Schulbuchgestaltung in Forschung und Schulpraxis

* [Dokumentation der Lehrveranstaltung](schulbuch/dokumentation.html)


## Stoffdidaktik Mathematik

* [Vorlesungsskript Wintersemester 2021/22](https://stoffdidaktik.heiko-etzold.de/2021)

* [Vorlesungsskript Wintersemester 2022/23](https://stoffdidaktik.heiko-etzold.de/2022)

* [Vorlesungsskript Wintersemester 2023/24](https://stoffdidaktik.heiko-etzold.de/2023)

* [Vorlesungsskript Wintersemester 2024/25](https://stoffdidaktik.heiko-etzold.de)


## Präsentationen

* 08.02.2022: [Bildung in der Digitalen Welt -- Algorithmisches Denken und Aufgabengestaltung im fächerübergreifenden Unterricht](praesis/2022-02-08-Etzold-AlgorithmenAufgaben.pdf)

* 01.09.2022: [Grundvorstellungen und Tätigkeitstheorie -- (Wie) passt das zusammen?](praesis/2022-09-01-Etzold-TaetigkeitstheorieGrundvorstellung.pdf) -- Vortrag zur GDM-Jahrestagung in Frankfurt/Main

* 08.12.2022: [Begriffsbildung zum Winkelfeld](praesis/2022-12-08-Etzold-Winkel.pdf) -- Gastvortrag an der TU Chemnitz im Rahmen der Lehrveranstaltung „Didaktik der Geometrie für die Grundschule“

* 12.06.2023: [Spielen, Falten, Experimentieren -- Wie soll das helfen, Mathematik zu verstehen?](praesis/2023-06-12-Etzold-SpielenFaltenExperimentieren.pdf) -- Vortrag im Rahmen des Eröffnungskolloquiums der Wanderausstellung „Mathematik zum Anfassen“ des Mathematikums Gießen am 12.06.2023 an der B-TU Cottbus

* 08.03.2024: [Lernmodelle zum Lösen von Gleichungen -- Eine Analyse und Weiterentwicklung aus tätigkeitstheoretischer Perspektive](praesis/2024-03-08-Etzold-Lernmodelle.pdf) -- Vortrag zur GDM-Jahrestagung in Essen

* 15.07.2024: [Tätigkeitstheorie als Mittel zum Zweck](praesis/2024-07-15-Etzold-Taetigkeitstheorie.pdf) -- Vortrag im Rahmen des mathematikdidaktischen Kolloquiums an der Universität Duisburg-Essen

* 18.07.2024: [Spiele im Mathematikunterricht](praesis/2024-07-18-Etzold-Spiele.pdf) -- Workshop im Rahmen des 11. Fachtages für Mathematik des Landes Brandenburg in Luckenwalde


